dist: trusty
sudo: required
language: generic

services:
  - docker

env:
  matrix:
  - COQ_IMAGE="coqorg/coq:8.4"
  - COQ_IMAGE="coqorg/coq:8.5"
  - COQ_IMAGE="coqorg/coq:8.6"
  - COQ_IMAGE="coqorg/coq:8.7"
  - COQ_IMAGE="coqorg/coq:8.8"
  - COQ_IMAGE="coqorg/coq:dev"

install: |
  # Tweak the Dockerfile
  sed -e "0,/^FROM/{s|\\(^FROM\\s\\).*\$|\\1$COQ_IMAGE|}" -i Dockerfile

script:
- echo -e "${ANSI_YELLOW}Building Demo...${ANSI_RESET}" && echo -en 'travis_fold:start:script\\r'
- docker build --pull -t demo .
- echo -en 'travis_fold:end:script\\r'
