dist: bionic
language: minimal

services:
  - docker

env:
  matrix:
  # TODO: remove unneeded versions below
  # - COQ_IMAGE="coqorg/coq:8.4"
  # - COQ_IMAGE="coqorg/coq:8.5"
  # - COQ_IMAGE="coqorg/coq:8.6"
  # - COQ_IMAGE="coqorg/coq:8.7"
  # - COQ_IMAGE="coqorg/coq:8.8"
  # - COQ_IMAGE="coqorg/coq:8.9"
  # - COQ_IMAGE="coqorg/coq:8.10"
  - COQ_IMAGE="coqorg/coq:8.11"
  - COQ_IMAGE="coqorg/coq:dev"

  # All these images contain $COMPILER as default switch.
  # This example uses $COMPILER_EDGE => see "opam switch" in Dockerfile
  # and https://github.com/coq-community/docker-coq/wiki#supported-tags

script:
- echo -e "${ANSI_YELLOW}Building Demo...${ANSI_RESET}" && echo -en 'travis_fold:start:script\\r'
- docker build --build-arg=coq_image="${COQ_IMAGE}" --pull -t demo .
- echo -en 'travis_fold:end:script\\r'
