dist: trusty
sudo: required
language: generic

services:
  - docker

env:
  matrix:
  - COQ_IMAGE="coqorg/coq:8.4"
  - COQ_IMAGE="coqorg/coq:8.5"
  - COQ_IMAGE="coqorg/coq:8.6"
  - COQ_IMAGE="coqorg/coq:8.7"
  - COQ_IMAGE="coqorg/coq:8.8"
  - COQ_IMAGE="coqorg/coq:8.9"
  - COQ_IMAGE="coqorg/coq:dev"

script:
- echo -e "${ANSI_YELLOW}Building Demo...${ANSI_RESET}" && echo -en 'travis_fold:start:script\\r'
- docker build --build-arg=coq_image="${COQ_IMAGE}" --pull -t demo .
- echo -en 'travis_fold:end:script\\r'
